version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t gabrielschmith/softplan-api:$CIRCLE_BUILD_NUM .
<<<<<<< HEAD
  test:
    machine: true
    steps:
      - checkout
      - run: docker build -f DockerfileTest -t gabrielschmith/softplan-api-test:$CIRCLE_BUILD_NUM .
      - run: docker run -it gabrielschmith/softplan-api-test:$CIRCLE_BUILD_NUM

=======
      - run: echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      - run: docker push gabrielschmith/softplan-api:$CIRCLE_BUILD_NUM
>>>>>>> 533de9435ae52d1253bfb57e143b1a664e11882b
workflows:
  version: 2
  build:
    jobs:
      - build
