version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t gabrielschmith/softplan-api:$CIRCLE_BUILD_NUM .
  test:
    machine: true
    steps:
      - checkout
      - run: docker build -f DockerfileTest -t gabrielschmith/softplan-api-test:$CIRCLE_BUILD_NUM .
      - run: docker run -it gabrielschmith/softplan-api-test:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
